// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef add_______h
#define add_______h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Choice.H>
extern void callback(Fl_Choice*, void*);
#include <FL/Fl_Button.H>
Fl_Double_Window* make_window();
#endif
