// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef alert_h
#define alert_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
Fl_Double_Window* make_window();
#endif
