// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "alert.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(253, 126);
    w = o;
    { Fl_Box* o = new Fl_Box(35, 24, 190, 76, "\346\267\273\345\212\240\346\210\220\345\212\237\357\274\201");
      o->box(FL_FLAT_BOX);
      o->labelsize(28);
    } // Fl_Box* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
