// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef avSalaryWin_h
#define avSalaryWin_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
extern Fl_Box *departmentNameBox;
extern Fl_Box *personCountBox;
#include <FL/Fl_Button.H>
extern Fl_Box *avgSalaryBox;
Fl_Double_Window* make_window();
#endif
