// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "avSalaryWin.h"

Fl_Box *departmentNameBox=(Fl_Box *)0;

Fl_Box *personCountBox=(Fl_Box *)0;

Fl_Box *avgSalaryBox=(Fl_Box *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(444, 251, "\345\237\272\346\234\254\345\267\245\350\265\204");
    w = o;
    { Fl_Group* o = new Fl_Group(30, 20, 400, 50);
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)159);
      { new Fl_Box(30, 20, 120, 50, "\351\203\250\351\227\250\345\220\215\347\247\260\357\274\232");
      } // Fl_Box* o
      { new Fl_Box(255, 20, 120, 50, "\351\203\250\351\227\250\344\272\272\346\225\260\357\274\232");
      } // Fl_Box* o
      { departmentNameBox = new Fl_Box(120, 20, 150, 50);
      } // Fl_Box* departmentNameBox
      { personCountBox = new Fl_Box(355, 20, 55, 50);
      } // Fl_Box* personCountBox
      o->end();
    } // Fl_Group* o
    { new Fl_Box(100, 104, 120, 56, "\351\203\250\351\227\250\345\271\263\345\235\207\345\267\245\350\265\204\357\
\274\232");
    } // Fl_Box* o
    { new Fl_Button(165, 180, 110, 50, "\347\241\256\345\256\232");
    } // Fl_Button* o
    { avgSalaryBox = new Fl_Box(205, 104, 125, 56);
    } // Fl_Box* avgSalaryBox
    o->end();
  } // Fl_Double_Window* o
  return w;
}
