// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef hrPagewin_h
#define hrPagewin_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
Fl_Double_Window* make_window();
#endif
