// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "hrPagewin.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(375, 135, "\347\224\267 \345\245\263");
    w = o;
    { new Fl_Button(30, 35, 135, 70, "\346\267\273\345\212\240\350\201\214\345\267\245");
    } // Fl_Button* o
    { new Fl_Button(215, 35, 135, 70, "\346\237\245\350\257\242\350\201\214\345\267\245");
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
