// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "loginwin.h"

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(306, 204);
    w = o;
    { Fl_Button* o = new Fl_Button(60, 140, 95, 50, "\347\231\273\351\231\206");
      o->callback((Fl_Callback*)loginCallback, (void*)(1));
    } // Fl_Button* o
    { Fl_Input* o = new Fl_Input(65, 32, 232, 36, "\347\224\250\346\210\267\345\220\215\357\274\232");
      o->labeltype(FL_SHADOW_LABEL);
    } // Fl_Input* o
    { new Fl_Input(65, 84, 232, 36, "\345\257\206\347\240\201   \357\274\232");
    } // Fl_Input* o
    { new Fl_Button(180, 140, 95, 50, "\346\263\250\345\206\214");
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}

void loginCallback(Fl_Widget*, void*) {
  printf("Hello, World!\n");
}
