// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef loginwin_h
#define loginwin_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
void loginCallback(Fl_Widget*, void*);
#endif
