// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "mainpageWin.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(647, 450, "\345\267\245\350\265\204\347\256\241\347\220\206\347\263\273\347\273\237_by\
\346\264\252\346\265\251\351\271\217");
    w = o;
    o->box(FL_BORDER_BOX);
    o->color((Fl_Color)91);
    { Fl_Button* o = new Fl_Button(120, 100, 175, 100, "\344\272\272\345\221\230\347\256\241\347\220\206");
      o->box(FL_ROUNDED_BOX);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(350, 255, 175, 100, "\345\267\245\350\265\204\347\256\241\347\220\206");
      o->box(FL_ROUNDED_BOX);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(125, 260, 175, 100, "\351\203\250\351\227\250\347\256\241\347\220\206");
      o->box(FL_ROUNDED_BOX);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(345, 100, 175, 100, "\347\263\273\347\273\237\347\256\241\347\220\206");
      o->box(FL_ROUNDED_BOX);
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
