// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef mainWindow_h
#define mainWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
static void loginCallback(Fl_Widget*,void* userdata);
#endif
