// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "mainWindow.h"

void loginCallback(Fl_Widget*,void* userdata) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(538, 386);
    w = o;
    o->end();
  } // Fl_Double_Window* o
}
