// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef mainpageWin_h
#define mainpageWin_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
Fl_Double_Window* make_window();
#endif
