// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef queryEmployeePage_h
#define queryEmployeePage_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Table.H>

class queryEmployeePage {
public:
  queryEmployeePage();
};
#endif
