// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "salaryTable.h"

Fl_Box *personNameBox=(Fl_Box *)0;

Fl_Box *departNameBox=(Fl_Box *)0;

Fl_Box *jobNameBox=(Fl_Box *)0;

Fl_Box *personGenderBox=(Fl_Box *)0;

Fl_Double_Window* make_window() {
	Fl_Double_Window* w;
	{ Fl_Double_Window* o = new Fl_Double_Window(561, 400, "\345\221\230\345\267\245\345\267\245\350\265\204");
	w = o;
	{ Fl_Table* o = new Fl_Table(25, 155, 520, 215, "\345\221\230\345\267\245\345\267\245\350\265\204\350\241\250");
	{ Fl_Table* o = new Fl_Table(50, 180, 15, 15);
	o->end();
	} // Fl_Table* o
	o->end();
	} // Fl_Table* o
	{ Fl_Group* o = new Fl_Group(25, 25, 520, 105, "\345\221\230\345\267\245\344\277\241\346\201\257");
	o->box(FL_FLAT_BOX);
	o->color((Fl_Color)166);
	{ new Fl_Box(45, 38, 65, 29, "\345\220\215\345\255\227\357\274\232");
	} // Fl_Box* o
	{ personNameBox = new Fl_Box(120, 38, 65, 29);
	} // Fl_Box* personNameBox
	{ new Fl_Box(45, 81, 65, 29, "\351\203\250\351\227\250\357\274\232");
	} // Fl_Box* o
	{ departNameBox = new Fl_Box(120, 81, 65, 29);
	} // Fl_Box* departNameBox
	{ new Fl_Box(260, 81, 65, 29, "\350\201\214\344\275\215\357\274\232");
	} // Fl_Box* o
	{ jobNameBox = new Fl_Box(330, 81, 65, 29);
	} // Fl_Box* jobNameBox
	{ new Fl_Box(260, 38, 65, 29, "\346\200\247\345\210\253\357\274\232");
	} // Fl_Box* o
	{ personGenderBox = new Fl_Box(330, 38, 65, 29);
	} // Fl_Box* personGenderBox
	o->end();
	} // Fl_Group* o
	o->end();
	} // Fl_Double_Window* o
	return w;
}
