// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef salaryTable_h
#define salaryTable_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Table.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
extern Fl_Box *personNameBox;
extern Fl_Box *departNameBox;
extern Fl_Box *jobNameBox;
extern Fl_Box *personGenderBox;
Fl_Double_Window* make_window();
#endif
