// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef ShouldAddAndSubPage_h
#define ShouldAddAndSubPage_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Spinner.H>

class ShouldAddAndSubPage {
public:
  ShouldAddAndSubPage();
  Fl_Input *personNumIP;
  Fl_Input *addsubIP;
  Fl_Spinner *moneySP;
  Fl_Spinner *yearSP;
  Fl_Spinner *monthSP;
  Fl_Spinner *daySP;
};
#endif
