// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "ShouldAddAndSubPage.h"

ShouldAddAndSubPage::ShouldAddAndSubPage() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(535, 433, "\345\272\224\345\242\236\345\272\224\345\207\217");
    w = o;
    o->user_data((void*)(this));
    { personNumIP = new Fl_Input(105, 22, 255, 43, "\345\221\230\345\267\245\347\274\226\345\217\267\357\274\232");
    } // Fl_Input* personNumIP
    { new Fl_Button(415, 22, 90, 43, "\346\237\245\350\257\242\345\221\230\345\267\245");
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(30, 100, 480, 100, "\345\221\230\345\267\245\344\277\241\346\201\257");
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)174);
      o->end();
    } // Fl_Group* o
    { addsubIP = new Fl_Input(105, 231, 162, 43, "\345\272\224\345\242\236\345\272\224\345\207\217\357\274\232");
    } // Fl_Input* addsubIP
    { moneySP = new Fl_Spinner(340, 231, 162, 43, "\351\207\221\351\242\235\357\274\232");
      moneySP->maximum(100000);
    } // Fl_Spinner* moneySP
    { yearSP = new Fl_Spinner(65, 301, 105, 43, "\345\271\264\357\274\232");
      yearSP->maximum(3000);
      yearSP->value(2015);
    } // Fl_Spinner* yearSP
    { monthSP = new Fl_Spinner(235, 301, 105, 43, "\346\234\210\357\274\232");
      monthSP->maximum(12);
    } // Fl_Spinner* monthSP
    { daySP = new Fl_Spinner(397, 301, 105, 43, "\346\227\245\357\274\232");
      daySP->maximum(31);
    } // Fl_Spinner* daySP
    { Fl_Button* o = new Fl_Button(105, 372, 90, 43, "\347\241\256\345\256\232");
      o->deactivate();
    } // Fl_Button* o
    { new Fl_Button(330, 372, 90, 43, "\345\217\226\346\266\210");
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
}
