// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef salaryManagePage_h
#define salaryManagePage_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Button.H>

class SalaryManagePage {
public:
	Fl_Window* container;
public:
  SalaryManagePage();
  void show();
};
#endif
